# Input file to set runtime parameters

[Heater]

  # Heater dimensions
  xmin = -48.0
  xmax = 48.0

  # Number of sites
  numSites = 3000

[Parfile]

  # Size of computational volume
  xmin = -50.0
  xmax = 50.0

  # AMR parameters
  nblockx = 200

  # Restart, checkpoint, and plotting options
  nend = 1200000
  tmax = 10
  checkpointFileIntervalTime = 10.0
  plotFileIntervalTime = 0.1

  # Overwrite tolerance
  gr_amrexMG_Tol = 1.0e-13

  # Write checkpoint file every xxxx
  # seconds of wall clock time. This
  # is useful to manage queue time. The
  # value below will write checkpoint
  # every 6000 seconds
  #wall_clock_checkpoint = 6000
  wall_clock_time_limit = 6000

  # Cycle through checkpoints 0-1 in
  # this case. This reduces the number
  # of checkpoints that are written.
  # Cyling just overwrites previous
  # checkpoints and only stores
  # the latest.
  rolling_checkpoint = 2

  restart = ".true."
  checkpointFileNumber = 2
  plotFileNumber = 0
